### ISSUE TITLE
Telegram link in the receive window is expired

### ISSUE THREAD

**Issue by dennisvanderpool** [mwcproject/mwc-wallet#14]
Just like the title mentioned. In the receive window of the Windows GUI wallet there is a Telegram link which is expired:

https://t.me/joinchat/IJTzpk33q3uBnautDTC5Sw

**Comment by bayk** [comment]
This issue is related to QT wallet:
I recreated it there https://github.com/mwcproject/mwc-qt-wallet/issues/900
This issue is closed
