### ISSUE TITLE
receiver wallet takes long to send slate back on starting.

### ISSUE THREAD

**Issue by yyangli** [mwcproject/mwc-wallet#4]
Build a new sending and receiver wallet and do a new send
sending wallet will do a full scan before sending
Sending wallet timed out before receiving slate back because receiving wallet takes a long time to send slate back.

**Comment by bayk** [comment]
Will be fixed in the next release. Here is a fix: https://github.com/mwcproject/mwc-wallet/commit/27b16f52fdcc0c2bb8c5be6a8c2de51e17282632
